---
# Main tasks file for {{ cookiecutter.ansible_role_name }} role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ '{{ role_path }}/tasks/manage_variables.yml' }}"
  tags:
    - 'role::{{ cookiecutter.ansible_role_name }}'
    - 'role::{{ cookiecutter.ansible_role_name }}::init'
